### ISSUE TITLE
Command schedule:run runs but command is not executed

### ISSUE THREAD

**Issue by parijke** [zenstruck/schedule-bundle#12]
I have a command that sends a list to  group of users. This works fine when I execute the command by hand (`bin/console app:MailOpenTodos`) . But in the scheduler it's not fired (the list does not appear).

I can see the entry with schedule:list and when the trigger time has been I can see it is scheduled to the next day, so the cronjob is running the schedule:run command.

What can be wrong?

Here's my schedule class:
```
class AppScheduleBuilder implements ScheduleBuilder
{
    public function buildSchedule(Schedule $schedule): void
    {
        $schedule
            ->timezone('Europe/Madrid')
            ->environments('prod');

        $schedule->addCommand('app:MailOpenTodos')
            ->description('Send the weekly report to users.')
            ->daily()->at("20:45");
    }
}
```

And this is the output from `schedule:list --detail`

```
1 Scheduled Task Configured
===========================

(1/1) CommandTask: Send the weekly report to users.
---------------------------------------------------

 ------------------- ---------------------------------------------------- 
  Command Name        app:MailOpenTodos                                   
  Command Arguments   (none)                                              
  Task ID             9039b82b7428839c1c6ac3e3cfcdeb462c9f703d            
  Task Class          Zenstruck\ScheduleBundle\Schedule\Task\CommandTask  
  Frequency           45 20 * * *                                         
  Next Run            Wed, Jul 15, 2020 @ 8:45 (Europe/Madrid +0200)      
 ------------------- ---------------------------------------------------- 

 // 1 Schedule Extension:                                                                                               

 * Only run in [prod] environment (Zenstruck\ScheduleBundle\Schedule\Extension\EnvironmentExtension)

 [OK] No schedule or task issues.       
```

**Comment by kbond** [comment]
Hmm, nothing jumps out at me, some questions:

1. The cron is being run in the production env?
2. The `schedule:run` cron task is running every minute?
3. Can you see logs for around the time the cron should have run? Anything telling there?

Does the command run as expected when you [run the task manually](https://github.com/zenstruck/schedule-bundle/blob/master/doc/run-schedule.md#force-run):

    bin/console schedule:run 9039b82b7428839c1c6ac3e3cfcdeb462c9f703d

**Comment by parijke** [comment]
Yes then it runs and I recieve the mail
```
[mkbeyo1q@www74 bo3.espunda.com]$ bin/console schedule:run 3872dd1b686d2255d5d7d95edb7532670e782049

 // Force Running 1 task. (1 total tasks)                                                                               

 Force Running CommandTask: Send the weekly report to users.
 Success. (Duration: 1 sec, Memory: 20.0 MiB)

                                                                                                                        
 [OK] 1/1 tasks ran, 1 succeeded. (Duration: 1 sec, Memory: 20.0 MiB) 
```

**Comment by kbond** [comment]
Ok, looks to be a cron job issue, what about questions 1-3 from my above comment?

**Comment by parijke** [comment]
yes it runs otherwise it would not change the schedule time. If the time arrives, the command schedule:list displays a next run fotr tomorrow which is good

**Comment by kbond** [comment]
> yes it runs otherwise it would not change the schedule time

This is not accurate: `schedule:list` just shows the "expected" next run. It doesn't confirm that the schedule is running as expected.

> The job runs every 5 mins

the cron job runs every 5 minutes? can you show the entry from your crontab?

**Comment by parijke** [comment]
It is a crontab from cpanel
```
*/5	*	*	*	*	cd /home/misite/sites/www.mysite.com && bin/console schedule:run	    
```

**Comment by kbond** [comment]
Was every 5 minutes the minimum CPanel allows? I don't think it would make a difference since you are running the task @ 8:45, but I might be wrong about that.

Does CPanel provide any output logging from the cron?

I'm trying to confirm your cron job is actually running `schedule:run` without error...

**Comment by parijke** [comment]
It is a cron job runs but it's not executing the command. I made sure the output is mailed to me, and the output is the output of bin/console withhout the schedule:run command

This is below the output....
`Warning: The console should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI` 

Don;t know why but I think it is indeed a cron issue

**Comment by kbond** [comment]
Hmm, longshot, but what happens when you put `php` in front of `bin/console`: 

    cd /home/mysite/sites/www.mysite.com && php bin/console schedule:run

**Comment by parijke** [comment]
I had to explicitely name the path of the php.... it now outputs  `! [NOTE] No tasks due to run. (1 total tasks)     `

**Comment by parijke** [comment]
So now it outputs as expected I am going to schedule it again

**Comment by kbond** [comment]
Excellent! Looks like that was the issue.

**Comment by parijke** [comment]
Now we wait a few mins
```
1/1) CommandTask: Send the weekly report to users.
---------------------------------------------------

 ------------------- ---------------------------------------------------- 
  Command Name        app:MailOpenTodos                                   
  Command Arguments   (none)                                              
  Task ID             5d0d81272b0bd5f1ad06a12ab81033a9e80d72d7            
  Task Class          Zenstruck\ScheduleBundle\Schedule\Task\CommandTask  
  Frequency           20 22 * * *                                         
  Next Run            Tue, Jul 14, 2020 @ 10:20 (Europe/Madrid +0200)     
 ------------------- ---------------------------------------------------- 
```

**Comment by parijke** [comment]
And.....
```

 // Running 1 due task. (1 total tasks)                                         

 Running CommandTask: Send the weekly report to users.
 Success. (Duration: 2 secs, Memory: 20.0 MiB)

 [OK] 1/1 tasks ran, 1 succeeded. (Duration: 2 secs, Memory: 20.0 MiB)         


```
Victory thanks for your help

**Comment by kbond** [comment]
No problem! Do you mind sharing the updated cron entry? I'm thinking I should change the documentation to prefix `bin/console` with `php`.

**Comment by parijke** [comment]
No problem it is this on a cpanel host
```

cd /home/mysite/sites/www.mysite.com && /opt/alt/php74/usr/bin/php /home/mysite/sites/www.mysite.com/bin/console schedule:run >> /dev/null 2>&1
```

It is a little bit verbose but it works

**Comment by kbond** [comment]
Perfect, thanks!
