### ISSUE TITLE
Configuration File for tasks should become a parameter

### ISSUE THREAD

**Issue by chess-server** [zenstruck/schedule-bundle#18]
I am running a website where I need to switch on/off the Cron Tasks, at least sometimes. I am therefore storing the commands in a table of the database and recreate the config file when it changes. This works in dev-environment of Symfony, but fails in prod, as the config file zenstruck_schedule.yaml in config/packages is no longer read. To avoid clearing cache anytime I change something, if would be helpful if one could enter
php bin/console scheduler:run -c path/to/configfile
with configfile e.g. in public. This file contains only the task array, not general configurations.
How can this be achieved?

**Comment by kbond** [comment]
So you have some kind of command or operation that generates `config/packages/zenstruck_schedule.yaml`?

**Comment by chess-server** [comment]
Yes, I created a special service "CronManager", which is called by the controller. I can add, delete, suspend and wake up commands. Only unsuspended commands are written into the config file. All commands, suspended or not are also stored in the database. 

Until recently I used an update of michelsalib/BCCCronManagerBundle but it suddenly stopped working. Maybe due to symfony 5.0. I do not have the time to work on that bundle, so I found this one. I carried over the handling routines, added the database table ilo of a file and then simply dump the yaml-file.

I would also like to see the possiblity to add log-files for the commands. So far I used a two-level logging: From inside the command about events to be locked and then a second level, which only mentioned success or errors. The dates from these files were shown in my overview. I am now taking the log from schedule:run, read it from the back and take the dates from the first apperance of a command to show Error or Success and latest run date.

**Comment by kbond** [comment]
I would avoid writing config files as like you say, you have to clear the cache for these changes to be picked up. I would create a [schedule builder service](https://github.com/zenstruck/schedule-bundle/blob/master/doc/define-schedule.md#schedulebuilder-service) that directly generates your schedule from the database:

```php
use Zenstruck\ScheduleBundle\Schedule;
use Zenstruck\ScheduleBundle\Schedule\ScheduleBuilder;

class DatabaseScheduleBuilder implements ScheduleBuilder
{
    // ...

    public function buildSchedule(Schedule $schedule): void
    {
        foreach ($this->getNonSuspendedTasks() as $taskConfig) {
            $task = $taskConfig->createTask(); // instance of Zenstruck\ScheduleBundle\Schedule\Task
            $schedule->add($task);
        }
    }
}
```

This way, the current task list that can be run is generated "on the fly".

**Comment by parijke** [comment]
This sounds cool and easy Kevin

**Comment by kbond** [comment]
Regarding your logging request, if I understand correctly, you want to log the status of the run in your database? I'm doing something similar, I used the [`AfterTaskEvent`](https://github.com/zenstruck/schedule-bundle/blob/master/doc/extending.md#events) to get the details and save this to the db.

**Comment by chess-server** [comment]
The ScheduleBuilder works like a charm! Thanks, really great solution. Saves the config file, the clear cache etc. 

I will also look into the AfterTaskEvent.

**Comment by chess-server** [comment]
After I understood the structure of the result, the AfterTaskEvent works as well. Thanks again.

One proposal: Offer an index field, which the user can use. E.g. to store the ID from the database table. Using the task description to search for the task might not be error proof enough.

**Comment by kbond** [comment]
> Offer an index field

Could the [Task ID](https://github.com/zenstruck/schedule-bundle/blob/master/doc/define-tasks.md#task-id) work for this purpose? It is a hash of the frequency and description so it does change when one of these does... In one of my apps, I use it as the "key" in the db.

**Comment by chess-server** [comment]
Thanks again for this advice. Yes, TaskID works as well. I can now even check for duplicates and issue a warning to the user that he started two similar cron tasks!
