### ISSUE TITLE
Process timeout

### ISSUE THREAD

**Issue by WarGeneration** [zenstruck/schedule-bundle#24]
Hi, im using your bundle and want to know, how can i set timeout for bash process with yaml config?

Now i get this error and want to increase timeout;
Exception: ProcessTimedOutException: The process "/home/theillko/work/inked.com.ua/bin/update.sh" exceeded the timeout of 60 seconds.

**Comment by kbond** [comment]
Hi @WarGeneration, this is not possible to configure in YAML. You can only [configure this in PHP](https://github.com/zenstruck/schedule-bundle/blob/master/doc/define-tasks.md#processtask).

PHP is the recommended method of building your schedule. YAML task config is there as a convenience for simple tasks.

**Comment by WarGeneration** [comment]
okay, thank you
