### ISSUE TITLE
Doesn't work on Symfony 3.4

### ISSUE THREAD

**Issue by adpeyre** [zenstruck/schedule-bundle#37]
Hi,

I would like to use this bundle on Symfony 3.4 but it doesn't work.
There are problems with DependencyInjection component.

````
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder".
````

Can you fix that ?

Thx :)

**Comment by kbond** [comment]
Hey @adpeyre,

I played with installing on 3.4. There are many more problems than the error you show above... Basically, this bundle isn't compatible with a standard-edition 3.4 app.

I'm going to tighten the min dependencies to make it clear it is for 4.4+.

**Comment by adpeyre** [comment]
I am disappointed but I understand. 
Thx for your bundle.

**Comment by kbond** [comment]
Thanks, and thanks for understanding. I do know the pain of being stuck on legacy versions of Symfony...
