### ISSUE TITLE
Support Request: will this work?

### ISSUE THREAD

**Issue by parijke** [zenstruck/schedule-bundle#57]
Only want to execute a certain task the 3rd Monday of March every year

```
$schedule->addCommand('app:my-command)
            ->description('My Command')
            ->skip(
                'all other mondays of March',
                function () {
                    return ((new Date('today')) != (new Date('third monday of march')));
                }
            )
            ->yearly()
            ->months(3)
            ->weeklyOn(1)
            ->at('09:00');
```

**Comment by parijke** [comment]
@kbond also something weird happened when trying this.

when I replace `->weeklyOn(1)` with `->mondays()` the next run was in 2027?

**Comment by kbond** [comment]
Hey! This should do it:

```diff
$schedule->addCommand('app:my-command)
            ->description('My Command')
            ->skip(
                'all other mondays of March',
                function () {
                    return ((new Date('today')) != (new Date('third monday of march')));
                }
            )
-           ->yearly()
            ->months(3)
-           ->weeklyOn(1)
+           ->mondays() 
            ->at('09:00');
```

`->yearly()` sets the full cron expression to January 1st, so you were changing the month but the day (1) was staying the same. When you changed to `->mondays()` it was finding the next time a Monday in March is also the 1st - 2027 I guess :)

**Comment by kbond** [comment]
Admittedly, the API is a tad confusing as you've found. I copied from Laravel and didn't give it much thought. Feels like there's room for improvement.

**Comment by parijke** [comment]
Excellent, thanks for explaining.
