### ISSUE TITLE
list of configurations

### ISSUE THREAD

**Issue by Ctucker9233** [zenstruck/schedule-bundle#75]
It would be useful to have documentation on available schedule configurations. In the example, I can see ->hourly() is one, but what about every minute or every five minutes?

**Comment by kbond** [comment]
Hello, is [this](https://github.com/zenstruck/schedule-bundle/blob/1.x/doc/define-tasks.md#fluent-expression-builder) what you're looking for?

**Comment by Ctucker9233** [comment]
Yes! That's it! I'll close as a non-issue.
