### ISSUE TITLE
Schedule skip configuration not recognisable

### ISSUE THREAD

**Issue by bobvandevijver** [zenstruck/schedule-bundle#79]
Example:

```php
$schedule->skip('Schedule disabled during deploy', fn (): bool => $this->isDeploying());
```

Becomes:

```
Filter Schedule callback: Zenstruck\ScheduleBundle\Schedule:165 (Zenstruck\ScheduleBundle\Schedule\Extension\CallbackExtension)
```

It is not recognisable which schedule this applies to if you have multiple schedules and the description is not shown either. I believe this can be improved by using a dedicated extension class that extends the `CallbackExtension`, so the relevant information can be stored in there and show in the overview.

**Comment by kbond** [comment]
Agreed, I think we can add an optional `$description` to `CallbackExtension` and, if set, use it in `CallbackExtension::__toString()`.
