### ISSUE TITLE
Per command `ionice` or `nice`

### ISSUE THREAD

**Issue by FluffyDiscord** [zenstruck/schedule-bundle#83]
Would it be possible to add configuration for using `ionice` and `nice` per symfony command? Right now it needs to be set globally, for example in the cron, for all commands/tasks.

**Comment by kbond** [comment]
Hi @FluffyDiscord, if I understand `ionice` and `nice` correctly, the only task type that would benefit would be the `ProcessTask`. I'm not sure how we could utilize for the other task types.

**Comment by FluffyDiscord** [comment]
These could be also used for `CommandTask`s. You might have some rather heavy bulk operations using commands and ensuring that command runs "at low priority" might just prevent the other server's services from fighting with resources

**Comment by kbond** [comment]
How could this work? The `CommandTask`'s are run in the same process as `schedule:run`.

**Comment by FluffyDiscord** [comment]
That's the thing. The bundle would need to spawn new process for each command that wants to use one/both of them.

**Comment by kbond** [comment]
Hmm, yeah, I think that's a bit out of scope. I'm looking to sunset and eventually deprecate\archive (once 5.4 is EOL) this library in favor of `symfony/scheduler`.
